FROM ubuntu:bionic

WORKDIR /srv

ARG GREMLIN_VER=3.3.2

RUN apt-get update

RUN apt-get install -y unzip wget openjdk-11-jdk

RUN wget https://archive.apache.org/dist/tinkerpop/$GREMLIN_VER/apache-tinkerpop-gremlin-server-$GREMLIN_VER-bin.zip

RUN unzip apache-tinkerpop-gremlin-server-$GREMLIN_VER-bin.zip

WORKDIR /srv/apache-tinkerpop-gremlin-server-$GREMLIN_VER

COPY gremlin-conf.yaml conf/gremlin-conf.yaml

EXPOSE 8182

ENTRYPOINT ["bin/gremlin-server.sh", "conf/gremlin-conf.yaml"]

